#!/usr/local/bin/node

console.log("Building config file...");

var fs = require('fs');
var child_process = require('child_process');
var Mustache = require('mustache');

var configs = {
  graphiteHost: process.env.GRAPHITE_HOST || "127.0.0.1",
  graphitePort: process.env.GRAPHITE_PORT || "8125",
  flushInterval: process.env.FLUSH_INTERVAL || 10000,
  deleteCounters: process.env.DELETE_COUNTERS || false,
  deleteGauges: process.env.DELETE_GAUGES || false,
  deleteTimers: process.env.DELETE_TIMERS || false,
  deleteSets: process.env.DELETE_SETS || false
}
console.log(JSON.stringify(configs, null, 5));

var configTemplate = fs.readFileSync("./config.js.mustache").toString()
fs.writeFileSync("./config.js", Mustache.render(configTemplate, configs));

var options = {
  stdio: "inherit"
}

child_process.spawnSync("node", ["./stats.js", "./config.js"], options);
